# Generated by Django 3.1 on 2020-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200824_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='accounts/profile/%Y/%m/%d/%H/%M/%s'),
        ),
    ]
