# Generated by Django 3.1 on 2020-08-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='360px * 360px 이하의 png/jpg 파일을 업로드 해주세요.', upload_to='accounts/profile_image/%Y/%m/%d/%H/%M/%S'),
        ),
    ]
